version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 651144116335.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t timeoff-mgmt .
      - docker tag timeoff-mgmt 651144116335.dkr.ecr.us-east-1.amazonaws.com/dev-timeoff-management:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 651144116335.dkr.ecr.us-east-1.amazonaws.com/dev-timeoff-management:latest